name: Build LaTeX document
on: push
jobs:
  build_latex_file:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
    - name: Check pdf file
      run: |
        file main.pdf | grep -q ' PDF '
    - name: Commit main.pdf
      run: |
        # configure git
        git config --global user.name "David Haberthür"
        git config --global user.email "email@davidhaberthuer.ch"
        # commit compiled file
        git add main.pdf
        git diff --exit-code HEAD -- output/main.pdf && exit 0
        git commit -m "[github actions] update compiled pdf"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, '[skip upload]')
