name: Build LaTeX document
on: push
jobs:
  build_latex_file:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
    - name: Check pdf file
      run: |
        file main.pdf | grep -q ' PDF '
    - name: Add and commit the PDF to the repository
      uses: srt32/git-actions@v0.0.3
        args: "git add main.pdf & git commit -m 'update main.pdf'"
