name: Build LaTeX document, check and commit to gh-pages branch
on:
  push:
    branches:
      - master
# The workflow schedule is defined by cron expression, e.g.: */4 11-13 * * * means this task will run every 4 minutes
# between 11-13 am UTC
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        latexmk_use_lualatex: true
    - name: Check pdf file
      run: |
        file main.pdf | grep -q ' PDF '
    - name: Upload
      run: |
        set -e

        # configure git
        # Here is the github name and email
        git config --global user.name "ACHDAirQuality"
        git config --global user.email "ACHD.AirQuality@gmail.com"

        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        # Copy and commit the PDF file
        mkdir -p "$GITHUB_WORKSPACE/deploy"
        cp -f main.pdf "$GITHUB_WORKSPACE/deploy/main.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git init
        git checkout --orphan gh-pages
        git add main.pdf
        git commit -m "[github actions] deploy"
        # here is the github repository link
        git remote add origin git@github.com:ACHDAirQuality/ACHD_Report_Generate.git
        git push --force --set-upstream origin gh-pages
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
